import Head from 'next/head';
import { Container, Row, Col } from 'react-bootstrap';
import NavigationBar from './components/NavigationBar';
import Menu from './components/Menu';
import { locations, menuItems } from '../constant/data';
import Carousel from './components/Carousel';
// import { useViewport } from '../Ultils/CustomHooks';
import Select from './components/Select';

export default function Home() {

  // const { width } = useViewport();

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>
      <main >
        <div className="w-100 menu-background">
          <Container className="p-0">
            <Row>
              <Col md={12} sm={12} xs={12} className="d-flex justify-content-center">
                <NavigationBar />
              </Col>
            </Row>
            {/* {width < 1024 && < Row >
              <Col md={12} sm={12} xs={12} className="d-flex justify-content-center">
                <Select
                  options={locations}
                  onSelected={() => { }}
                  setOverlay={() => {
                    console.log('click');
                  }}
                  isMobile
                />
              </Col>
            </Row>} */}
          </Container>
        </div>
        <div className="w-100 mt-4">
          <Container className="p-0">
            <Row className="justify-content-center">
              <Col md={2} sm={2} xs={2} className="margin-container-body">
                <Menu menuItems={menuItems} />
              </Col>
              <Col md={7} sm={7} xs={7}>
                <div className="slider-container" id="slider">
                  <Carousel />
                </div>
              </Col>
              <Col xs={2} className="d-flex flex-column justify-content-between right-coontainer">
                <Row>
                  <Col xs={12}>
                    <img src="https://cdn.cellphones.com.vn/media/ltsoft/promotion/photo_2021-04-23_11-41-15.jpg" height="115px" width="100%"></img>
                  </Col>
                </Row>
                <Row>
                  <Col xs={12}>
                    <img src="https://cdn.cellphones.com.vn/media/ltsoft/promotion/iPhone_12_690x300_copy_3_.png" height="115px" width="100%"></img>
                  </Col>
                </Row>
                <Row>
                  <Col xs={12}>
                    <img src="https://cdn.cellphones.com.vn/media/ltsoft/promotion/Right_banner.jpg" height="115px" width="100%"></img>
                  </Col>
                </Row>
              </Col>
              <Col md={12} sm={12} xs={12} className="d-flex justify-content-center mt-4">
                <img src="https://cdn.cellphones.com.vn/media/wysiwyg/1200x75-n20.png" className="img-fluid"></img>
              </Col>
            </Row>
          </Container>
        </div>

      </main>
    </div >
  )
}
